social_moodle_iteration_invite.settings:
  type: config_object
  label: 'Social Moodle Iteration Invite Settings'
  mapping:
    invite_subject:
      type: string
      label: 'The invite email subject.'
    invite_message:
      type: text
      label: 'The invite email message body.'
    invite_helper:
      type: text
      label: 'The invite helper text.'
