services:
  social_moodle_application.application_guard:
    class: Drupal\social_moodle_application\Guard\ApplicationGuard
    arguments: ['@current_user', '@plugin.manager.workflow']
    tags:
      - { name: state_machine.guard, group: application }

  social_moodle_application.workflow.helper:
    class: Drupal\social_moodle_application\WorkflowHelper
    arguments: ['@current_user']

  social_moodle_application.workflow_transition:
    class: Drupal\social_moodle_application\EventSubscriber\WorkflowTransitionEventSubscriber
    arguments: ['@social_moodle_application.workflow.helper']
    tags:
      - { name: event_subscriber }

  social_moodle_application.application_receipt_approve_supervisor_subscriber:
    class: Drupal\social_moodle_application\EventSubscriber\ApplicationReceiptApproveSupervisorSubscriber
    arguments: ['@entity_type.manager','@social_moodle_mail.mail_message_deliverer']
    tags:
      - { name: 'event_subscriber' }

  social_moodle_application.application_receipt_approve_lnd_subscriber:
    class: Drupal\social_moodle_application\EventSubscriber\ApplicationReceiptApproveLndSubscriber
    arguments: ['@entity_type.manager','@social_moodle_mail.mail_message_deliverer']
    tags:
      - { name: 'event_subscriber' }

  social_moodle_application.application_receipt_deny_supervisor_subscriber:
    class: Drupal\social_moodle_application\EventSubscriber\ApplicationReceiptDenySupervisorSubscriber
    arguments: ['@entity_type.manager','@social_moodle_mail.mail_message_deliverer']
    tags:
      - { name: 'event_subscriber' }

  social_moodle_application.application_receipt_deny_lnd_subscriber:
    class: Drupal\social_moodle_application\EventSubscriber\ApplicationReceiptDenyLndSubscriber
    arguments: ['@entity_type.manager','@social_moodle_mail.mail_message_deliverer']
    tags:
      - { name: 'event_subscriber' }

  social_moodle_application.application_receipt_wait_subscriber:
    class: Drupal\social_moodle_application\EventSubscriber\ApplicationReceiptWaitSubscriber
    arguments: ['@entity_type.manager','@social_moodle_mail.mail_message_deliverer']
    tags:
      - { name: 'event_subscriber' }

