services:
  social_moodle_application.application_guard:
    class: Drupal\social_moodle_application\Guard\ApplicationGuard
    arguments: ['@current_user', '@plugin.manager.workflow']
    tags:
      - { name: state_machine.guard, group: application }
  social_moodle_application.workflow.helper:
    class: Drupal\social_moodle_application\WorkflowHelper
    arguments: ['@current_user']
  social_moodle_application.workflow_transition:
    class: Drupal\social_moodle_application\EventSubscriber\WorkflowTransitionEventSubscriber
    arguments: ['@social_moodle_application.workflow.helper']
    tags:
      - { name: event_subscriber }
