social_moodle.settings:
  type: config_object
  label: 'Social Moodle Settings'
  mapping:
    social_moodle_group_types:
      type: sequence
      label: 'For which group type the social moodle feature is turned on.'
      group_type:
        type: string
        label: 'Group Type'
