<?php

/**
 * @file
 * Contains social_moodle_enrollment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;


function social_moodle_enrollment_get_supervisor_users($supervisor) {

	$users = FALSE;

	$database = \Drupal::database();
	$query = $database->select('profile', 'p');
	$query->fields('p', ['uid']);
	$query->join('profile__field_supervisor', 'ps', 'p.profile_id = ps.entity_id');
	$query->condition('ps.field_supervisor_target_id', $supervisor, '=');
	$result = $query->execute();

	if ($result) {
    foreach($result as $value) {
	    $users[$value->uid] = $value->uid;
    }
	}
	
	return $users;

}

function social_moodle_enrollment_get_users_supervisor($user) {

	$supervisor = FALSE;

	$database = \Drupal::database();
	$query = $database->select('profile', 'p');
	$query->fields('ps', ['field_supervisor_target_id']);
	$query->join('profile__field_supervisor', 'ps', 'p.profile_id = ps.entity_id');
	$query->condition('p.uid', $user, '=');
	$result = $query->execute();

	if ($result) {
    foreach($result as $value) {
      $supervisor = $value->field_supervisor_target_id;
    }
	}
	
	return $supervisor;

}


