social_moodle_iteration_managers.settings:
  type: config_object
  label: 'Social Moodle Iteration Managers Settings'
  mapping:
    author_as_manager:
      type: bool
      label: 'Whether the author of an event is automatically an Iteration organiser.'
